### ISSUE TITLE
Syntax mistakes

### ISSUE THREAD

**Issue by zachfedor** [Tfink13/more-css-practice#3]
https://github.com/Tfink13/more-css-practice/blob/3165effd1648114df896d319c586b31c212a92ed/airbnb/styles.css#L59

Watch out for syntax mistakes, they can cause issues with other parts of your code. This closing bracket looks orphaned, you should remove it.

**Comment by zachfedor** [comment]
https://github.com/Tfink13/more-css-practice/blob/3165effd1648114df896d319c586b31c212a92ed/amazon/index.html#L24

I'm not sure what's going on with your image sources here. It looks like you copied and pasted some extra characters. It looks like it's working, but they should probably be fixed up just in case.

**Comment by Tfink13** [comment]
thanks mane
