### ISSUE TITLE
Orginization

### ISSUE THREAD

**Issue by closetmouse2** [Tfink13/more-css-practice#5]
After reviewing a few of your indexes and stylesheets, I was actually pretty hard-pressed to find any issues that Prof. Fedor didn't already cover. So kudos for that! However, what I did notice was that your code is very hard to read. I would suggest adding more semantic containing elements to split the code up. Also make sure Parent and child elements are spaced appropriately (for viewing comfort).

**Comment by Tfink13** [comment]
Thanks
